spring.application.name=bff-atm-service
server.port=8083
core.banking.base-url=http://localhost:8080

# Clave simulada de autenticacion del canal cajero (header X-ATM-KEY)
atm.security.api-key=ATM-SECRET-2026
